#!/bin/sh

# this is a script file
# it should print to stdout a line for each test

echo ":manual 01"
echo ":manual 02"

for M in {10, 20, 50}
do
    echo "gen_rand -$M $M"
done

for M in {10, 20, 50}
do
    echo "gen_rand -$M 0"
done

